### PR TITLE
New Securtiy TRG´s

### PR DESCRIPTION
**Pull request by klaudiaZF**
Hi All,

Can you please tell me what you think? Do you have any feedback regarding our TRG?

### CODE REVIEW

**Comment by FaGru3n** [comment]
Hi @klaudiaZF, 

thanks for your input and your work, overall really needfull information.

Guess your title of the PR for TRG is a bit missleading maybe add new securtiy trg´s 😉 

feedback: 

- trg 8-3 is IMHO a guideline how to use your repo and how to contact you and i would move it to the README.md for `sig-security` 
- for the other to new TRG´s (Tractus-X Release Guidelines) i questioned myself, is this full needed for the upcomming release or is this just an information, how to use the security tools and process to check? 

IMHO such information which tools we have to use should be explicit mentioned as "you have to" like should / must do this for the release.

**Review by FaGru3n — CHANGES_REQUESTED** [review]
Sorry dind´t see that this is a total different Org and Repo so basically wrong... here sorry

**Comment by klaudiaZF** [comment]
Hi @FaGru3n it's not new, because we didn't add any security TRG yet

trg 8-3 is providing a steps and in our README file we have only information and links

Is an information how to use security tools and process

I move it to the right place... sorry for that

**Comment by FaGru3n** [comment]
Thank you for that ... 

👍🏼

**Pull request closed without merging**
